name: CI

on: push

jobs:
  specs:
    name: Ruby ${{ matrix.ruby }} using ${{ matrix.gemfile }}
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '2.6'
          - '2.7'
        gemfile:
          - rails4.2
          - rails5.1
          - rails5.2
          - rails6.0
          - rails6.1
          - rails7.0
        exclude:
          - {ruby: '2.7', gemfile: rails4.2}
          - {ruby: '2.6', gemfile: rails7.0}
    steps:
      - uses: zendesk/checkout@v3
      - uses: zendesk/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rspec

  specs_successful:
    name: Specs passing?
    needs: specs
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: |
          if ${{ needs.specs.result == 'success' }}
          then
            echo "All specs pass"
          else
            echo "Some specs failed"
            false
          fi
